version: '3'
services:
  mongodb:
    image: mongo:7.0.4
    container_name: node-gmp-mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_user_password
      MONGO_INITDB_DATABASE: mongo_db
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
